name: Update README with Repo Cards

on:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday at 00:00 UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # Ref MUST match your default branch (e.g. main or master)
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests
        run: pip install requests

      - name: Run script to update README
        run: python .github/scripts/generate_repo_cards.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git add README.md
            git commit -m "🤖 Update repo cards in README"
            git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          fi
